name: Call Trivy
on:
 push:
   branches: [master]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: easlank/actions/.github/workflows/reusable-trivy.yml@master
   with:
     image: 'ghcr.io/easlank/wordsmith-web:latest'
